services:

  api1: &api
    image: pedrorapos0/rinha-backend-2025-node
    hostname: api1
    environment:
      - APP_PORT=8080
      - REDIS_URL=redis:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
    depends_on:
      redis:
          condition: service_started
    ports:
      - "8080:8080"      

  redis:
    image: redis:latest
    container_name: rinha-redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "275MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true